export const ActionTypes = {
   FETCH_ARTICLES: 'FETCH_ARTICLES',
   FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
   FETCH_ARTICLES_FAILURE: 'FETCH_ARTICLES_FAILURE',
   PERSIST_ARTICLE_SUCCESS: 'PERSIST_ARTICLE_SUCCESS',

   FETCH_TAGS: 'FETCH_TAGS',
   FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
   FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE'
};
